### ISSUE TITLE
What happened to the old throttled library?

### ISSUE THREAD

**Issue by tellnes** [isuttell/throttled#1]
I have a few projects depending on it.

Btw, you should start your new versions with a major version bump. You can't do a more breaking change than this.

**Comment by isuttell** [comment]
I think you have the wrong repo and wrong author. If you check the commit history, I've made two commits to it 6 months ago. So, I'm guessing you're thinking of another project.

**Comment by tellnes** [comment]
Yes, I'm thinking of the projects which is is published on npm with version number `0.0.0` and `0.0.1`

Yes I know it is some time ago. I did not see this before now because I was using '~0.0.1' as version range.
